[package]
name = "poker"
version = "0.1.0"
authors = ["Michael Fletcher <m.fletcher@theplanet.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
